modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="klprod"
version="1.0"
displayName="KLProd Mod"
description='''Мод с изумрудной, редстоуновой и лазуритной бронёй и инструментами'''
